all:
	javac -cp .:lib/* exportTweet.java
	javac -cp .:lib/* exportTwitterGUI.java

twitter:
	javac -cp .:lib/* exportTweet.java
	java -cp .:lib/* exportTweet

twitterGUI:
	javac -cp .:lib/* exportTwitterGUI.java
	java -cp .:lib/* exportTwitterGUI

clean:
	rm -f *.class
